version: "3"
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - /data:/data/db

  api:
    image: chacachiene/irrigation:latest
    build: .
    platform: linux/amd64
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1307x2Npk
      - POSTGRES_DB=db
      - POSTGRES_PORT=5432
      - SECRET_KEY = "secret"
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db




volumes:
  postgres_data:

