"""farmer unique

Revision ID: bf34d1d99d91
Revises: 3494d82670dc
Create Date: 2024-05-19 16:35:52.482580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bf34d1d99d91'
down_revision: Union[str, None] = '3494d82670dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'farmer', ['value'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'farmer', type_='unique')
    # ### end Alembic commands ###
