"""script_fix

Revision ID: ea73fe6ea1fc
Revises: 1aadfaa8e8d6
Create Date: 2024-05-23 17:10:02.448770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ea73fe6ea1fc'
down_revision: Union[str, None] = '1aadfaa8e8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('script', sqlmodel.sql.sqltypes.AutoString(), nullable=True))



def downgrade() -> None:

    op.drop_column('farm', 'script')
    # ### end Alembic commands ###
